# Generated by Django 5.2 on 2025-04-16 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('designers', '0002_alter_designer_especialidade'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='designer',
        ),
        migrations.AddField(
            model_name='projeto',
            name='designers',
            field=models.ManyToManyField(related_name='projetos', to='designers.designer'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='cliente.cliente'),
        ),
    ]
