# Generated by Django 5.2 on 2025-04-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='tipo',
            field=models.CharField(choices=[('video', 'Edição de Vídeo'), ('social_media', 'Social Media'), ('design', 'Designer Gráfico')], default='design', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Base (R$)'),
        ),
    ]
