# Generated by Django 5.2 on 2025-04-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servicos_tipo_alter_servicos_preco_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
