# Generated by Django 5.2 on 2025-04-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servicos_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='ativo',
        ),
    ]
