# Generated by Django 5.2 on 2025-04-10 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projeto', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprovado', models.BooleanField(default=False)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
                ('servicos', models.ManyToManyField(to='servicos.servicos')),
            ],
        ),
    ]
