# Generated by Django 5.2 on 2025-04-16 02:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
        ('projeto', '0002_remove_projeto_designer_projeto_designers_and_more'),
        ('servicos', '0004_remove_servicos_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='projeto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='servicos',
            field=models.ManyToManyField(related_name='orcamentos', to='servicos.servicos'),
        ),
    ]
