# Generated by Django 5.2 on 2025-04-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='especialidade',
            field=models.CharField(choices=[('designer', 'Designer Gráfico'), ('social_media', 'Social Media'), ('videomaker', 'Videomaker')], max_length=50),
        ),
    ]
